spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abc?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://47.112.232.249:3306/abc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://47.112.232.249:3306/abc?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true

  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/
server:
  port: 8080


